version: '3.8'

services:
  backend:
    build: .
    container_name: contractge-backend
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - contractge-network

networks:
  contractge-network:
    driver: bridge 